[package]
name = "hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
la-arena.workspace = true

syntax.workspace = true
base-db.workspace = true
rustc-hash.workspace = true
smol_str = "0.1.24"
