[package]
name = "ide-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base-db.workspace = true
syntax.workspace = true
hir.workspace = true
