[package]
name = "base-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salsa = "0.17.0-pre.2"
paths.workspace = true
syntax.workspace = true
test-utils.workspace = true
tracing.workspace = true
